### ISSUE TITLE
Compatibility issue with MTS mod (wrench not working)

### ISSUE THREAD

**Issue by Philma-A-Hoal** [fonnymunkey/RLCombat#8]
Just a small bug that occurs anytime I install RLCOMBAT with MTS mod (Immersive Vehicles)

Shift + Left Click with an MTS (Immersive Vehicles) wrench no longer picks up any vehicle/plane.

tested with minimum mods. 

UNU Civilian Pack 1.12.2 22.5.0 - Beta3
MTS Official 1.12.2 v25 
Immersive Vehicles 1.12.2 22.9.0
RLCombat  1.12.2 - 2.0.8

Tried rebinding, and even unbinding many (almost all) key binds with no success.

Tried removing RLCombat from RLCraft modpack but with RLMixins installed, this causes a crash. 

[**EDIT**] Since I am using the RLCraft Modpack, "RLCOMBAT" isn't a totally necessary mod for everything else to work. I have figured out that if you disable all RLCombat related config options in /rlcraft/config/rlmixins, then you can load everything else including RLMixins without crashing, and still fix the wrench not picking up vehciles. (A temp fix until possibly patched)

**Comment by Philma-A-Hoal** [comment]
[**EDIT**] Since I am using the RLCraft Modpack, "RLCOMBAT" isn't a totally necessary mod for everything else to work. I have figured out that if you disable all RLCombat related config options in /rlcraft/config/rlmixins, then you can load everything else including RLMixins without crashing, and still fix the wrench not picking up vehciles. (A temp fix until possibly patched)

**Comment by fonnymunkey** [comment]
RLCombat is absolutely a necessary mod for RLCraft, MTS on the other hand isn't, since MTS does not come with RLCraft whereas RLCombat does.

RLCombat already has a blacklist for entities in the config, if the MTS mod is doing stuff where you need to attack its entities to interact, then add those entities to the blacklist.
ex;
minecrafttransportsimulator.entities.components.AEntityE_Interactable
or 
minecrafttransportsimulator.entities.instances.APart
or whichever entity it is that you can not interact with;
https://github.com/DrprofLuigi/MinecraftTransportSimulator/tree/master/mccore/src/main/java/minecrafttransportsimulator/entities

**Comment by Philma-A-Hoal** [comment]
Ah, understood. 
I saw this in the config options but wasn't exactly how to key it in.
Thank you for the quick reply!
